version: "2"

services:
  minidlna:
    image: robvde/rpi-samba:1.0
    volumes:
      - /mnt/mediadisk:/mnt/mediadisk
      - /home/pi/rpi-samba:/etc/rpi-samba
    ports:
      - 135:135/udp
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
      - 111:111/udp 
      - 111:111/tcp 
      - 2049:2049/tcp 
      - 2049:2049/udp
    restart: always 